// // // This file is automatically generated. Do not edit it directly.
// import { createClient } from "@supabase/supabase-js";
// import type { Database } from "./types";

// const SUPABASE_URL = "https://ltjlswzrdgtoddyqmydo.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY =
//   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0amxzd3pyZGd0b2RkeXFteWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDA5OTIsImV4cCI6MjA2MDExNjk5Mn0.YXg-x4oflJUdoRdQQQGI2NisUqUVHAXkhgyrr-4CoE0";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     autoRefreshToken: true,
//     persistSession: true,
//     detectSessionInUrl: true,
//   },
// });

// integrations/supabase/client.ts
// import { createClient } from "@supabase/supabase-js";
// import type { Database } from "./types";

// const SUPABASE_URL = "https://ltjlswzrdgtoddyqmydo.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY =
//   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0amxzd3pyZGd0b2RkeXFteWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDA5OTIsImV4cCI6MjA2MDExNjk5Mn0.YXg-x4oflJUdoRdQQQGI2NisUqUVHAXkhgyrr-4CoE0";

// const COOKIE_NAME = "sb-auth-token";

// function getCookie(name: string) {
//   const match = document.cookie.match(new RegExp("(^| )" + name + "=([^;]+)"));
//   return match ? decodeURIComponent(match[2]) : null;
// }

// function setCookie(name: string, value: string, days = 7) {
//   const expires = new Date(Date.now() + days * 864e5).toUTCString();
//   document.cookie = `${name}=${encodeURIComponent(value)}; expires=${expires}; path=/; SameSite=Lax`;
// }

// function deleteCookie(name: string) {
//   document.cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/`;
// }

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     autoRefreshToken: true,
//     persistSession: true,
//     detectSessionInUrl: true,
//   },
// });

// // 🔄 Keep cookie updated when session changes
// supabase.auth.onAuthStateChange((_, session) => {
//   if (session?.access_token) {
//     setCookie(COOKIE_NAME, JSON.stringify(session));
//   } else {
//     deleteCookie(COOKIE_NAME);
//   }
// });

// // 🔁 Restore session from cookie (used in App.tsx)
// export async function restoreSessionFromCookie() {
//   const cookieValue = getCookie(COOKIE_NAME);
//   if (cookieValue) {
//     try {
//       const session = JSON.parse(cookieValue);
//       if (session?.access_token) {
//         await supabase.auth.setSession(session);
//         console.log("✅ Restored session from cookie");
//         return session;
//       }
//     } catch (e) {
//       console.error("Failed to parse cookie session:", e);
//     }
//   }
//   return null;
// }

// integrations/supabase/client.ts
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * 🧠 Purpose:
 * - Keeps session alive after tab inactivity or browser sleep
 * - Automatically restores session from cookie
 * - Ensures Realtime reconnection on tab focus
 * - Fixes query timeout issues after long idle periods
 */

const SUPABASE_URL = "https://ltjlswzrdgtoddyqmydo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0amxzd3pyZGd0b2RkeXFteWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDA5OTIsImV4cCI6MjA2MDExNjk5Mn0.YXg-x4oflJUdoRdQQQGI2NisUqUVHAXkhgyrr-4CoE0";

const COOKIE_NAME = "sb-auth-token";

/* ----------------------- Cookie Helpers ----------------------- */
function getCookie(name: string) {
  const match = document.cookie.match(new RegExp("(^| )" + name + "=([^;]+)"));
  return match ? decodeURIComponent(match[2]) : null;
}

function setCookie(name: string, value: string, days = 7) {
  const expires = new Date(Date.now() + days * 864e5).toUTCString();
  document.cookie = `${name}=${encodeURIComponent(value)}; expires=${expires}; path=/; SameSite=Lax`;
}

function deleteCookie(name: string) {
  document.cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/`;
}

/* ----------------------- Supabase Client ----------------------- */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 5,
    },
  },
});

/* ----------------------- Auth State Sync ----------------------- */
supabase.auth.onAuthStateChange(async (event, session) => {
  console.log(`🔐 Auth state changed: ${event}`, session ? 'has session' : 'no session');
  
  // CRITICAL FIX: Only delete cookie on explicit SIGN_OUT
  // Don't delete on every null session (could be temporary state)
  if (event === "SIGNED_OUT") {
    console.log("🔐 User signed out - clearing cookie");
    deleteCookie(COOKIE_NAME);
    stopPeriodicBackup(); // Stop the periodic backup
  } else if (session?.access_token) {
    // Validate session hasn't expired before saving
    const expiresAt = session.expires_at ? session.expires_at * 1000 : 0;
    const isExpired = expiresAt > 0 && Date.now() >= expiresAt;
    
    if (!isExpired) {
      setCookie(COOKIE_NAME, JSON.stringify(session));
      console.log("💾 Session saved to cookie backup");
      
      // Start periodic backup if not already running
      if (event === "SIGNED_IN" || event === "TOKEN_REFRESHED") {
        startPeriodicBackup();
      }
    } else {
      console.warn("⚠️ Session expired, not saving to cookie");
    }
  }

  if (event === "TOKEN_REFRESHED") {
    console.log("🔁 Token refreshed successfully");
  }
});

/* ----------------------- Restore Session ----------------------- */
export async function restoreSessionFromCookie() {
  console.log("🍪 Attempting to restore session from cookie...");
  const cookieValue = getCookie(COOKIE_NAME);
  
  if (!cookieValue) {
    console.warn("🍪 No session cookie found");
    return null;
  }
  
  console.log("🍪 Cookie found, parsing...");
  
  try {
    const session = JSON.parse(cookieValue);
    
    if (!session?.access_token) {
      console.warn("🍪 Cookie exists but no access_token found");
      deleteCookie(COOKIE_NAME);
      return null;
    }
    
    // Validate session hasn't expired
    const expiresAt = session?.expires_at ? session.expires_at * 1000 : 0;
    const isExpired = expiresAt > 0 && Date.now() >= expiresAt;
    
    if (isExpired) {
      console.warn("🍪 Cookie session expired, clearing");
      deleteCookie(COOKIE_NAME);
      return null;
    }
    
    console.log("🍪 Cookie session valid, restoring to Supabase...");
    
    // CRITICAL: Set session in Supabase client (updates localStorage)
    const { data, error } = await supabase.auth.setSession({
      access_token: session.access_token,
      refresh_token: session.refresh_token
    });
    
    if (error) {
      console.error("🍪 Failed to set session:", error);
      deleteCookie(COOKIE_NAME);
      return null;
    }
    
    if (!data.session) {
      console.warn("🍪 setSession succeeded but returned no session");
      return null;
    }
    
    console.log("✅ Successfully restored session from cookie");
    
    // Re-save to cookie with updated expiry
    setCookie(COOKIE_NAME, JSON.stringify(data.session));
    
    // Start periodic backup
    startPeriodicBackup();
    
    return data.session;
  } catch (e) {
    console.error("❌ Failed to parse or restore cookie session:", e);
    deleteCookie(COOKIE_NAME);
    return null;
  }
}

/* ----------------------- Force Save Session ----------------------- */
export function forceSessionBackup(session: any) {
  if (session?.access_token) {
    // Validate session isn't expired
    const expiresAt = session.expires_at ? session.expires_at * 1000 : 0;
    const isExpired = expiresAt > 0 && Date.now() >= expiresAt;
    
    if (!isExpired) {
      setCookie(COOKIE_NAME, JSON.stringify(session));
      console.log("💾 Forced session backup to cookie");
      return true;
    } else {
      console.warn("⚠️ Session expired, not backing up");
      return false;
    }
  }
  return false;
}

/* ----------------------- Periodic Session Backup ----------------------- */
let periodicBackupInterval: NodeJS.Timeout | null = null;

function startPeriodicBackup() {
  // Don't start if already running
  if (periodicBackupInterval) {
    console.log("⏰ Periodic backup already running");
    return;
  }
  
  console.log("⏰ Starting periodic session backup (every 30s)");
  
  periodicBackupInterval = setInterval(async () => {
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (session?.access_token) {
        const saved = forceSessionBackup(session);
        if (saved) {
          console.log("⏰ Periodic session backup successful");
        }
      } else {
        console.log("⏰ No active session to backup");
        stopPeriodicBackup();
      }
    } catch (error) {
      console.error("⏰ Periodic backup error:", error);
    }
  }, 30000); // Every 30 seconds
}

function stopPeriodicBackup() {
  if (periodicBackupInterval) {
    clearInterval(periodicBackupInterval);
    periodicBackupInterval = null;
    console.log("⏰ Stopped periodic session backup");
  }
}

/* ----------------------- Realtime Reconnect Logic ----------------------- */
let reconnectTimeout: NodeJS.Timeout | null = null;

function reconnectRealtime() {
  if (reconnectTimeout) clearTimeout(reconnectTimeout);
  reconnectTimeout = setTimeout(async () => {
    try {
      console.log("🔌 Reconnecting Supabase Realtime...");
      // CRITICAL FIX: Don't check for session here - it creates a race condition
      // The visibilityCoordinator will restore the session separately (takes ~800ms)
      // Just reconnect - Supabase will use the restored session automatically
      await supabase.realtime.connect();
      console.log("🟢 Realtime reconnection initiated");
    } catch (error) {
      console.error("❌ Realtime reconnection failed:", error);
    }
  }, 1500); // Increased delay to allow session restoration to complete first
}

/* ----------------------- Handle Visibility Events ----------------------- */
// NOTE: Session restoration is handled by visibilityCoordinator in UnifiedAuthContext
// This listener ONLY manages Realtime connection state
if (typeof document !== "undefined") {
  document.addEventListener("visibilitychange", async () => {
    if (document.hidden) {
      console.log("👀 Tab hidden — disconnecting Realtime temporarily...");
      supabase.realtime.disconnect();
      
      // CRITICAL FIX: Force immediate backup before tab becomes hidden
      try {
        const { data: { session } } = await supabase.auth.getSession();
        if (session?.access_token) {
          const backed = forceSessionBackup(session);
          if (backed) {
            console.log("💾 Pre-hide session backup successful");
          }
        }
      } catch (error) {
        console.error("❌ Pre-hide backup failed:", error);
      }
    } else {
      console.log("👀 Tab visible again — reconnecting Realtime...");
      // Session restoration happens in UnifiedAuthContext via coordinator
      reconnectRealtime();
    }
  });
}

/* ----------------------- Health Ping & Auto-Start ----------------------- */
// Keeps connection warm in long-running sessions
setInterval(
  async () => {
    const { data } = await supabase.auth.getSession();
    if (data?.session?.access_token) {
      console.log("💓 Supabase session still active");
      // Ensure backup is running for active sessions
      if (!periodicBackupInterval) {
        startPeriodicBackup();
      }
    }
  },
  10 * 60 * 1000,
); // every 10 minutes

// Auto-start periodic backup if user is already logged in
(async () => {
  const { data: { session } } = await supabase.auth.getSession();
  if (session?.access_token) {
    console.log("🚀 Auto-starting periodic backup for existing session");
    forceSessionBackup(session);
    startPeriodicBackup();
  }
})();
